version: "3.8"

services:
    booksaw-api:
        image: souliks/booksaw-api:latest
        container_name: booksaw-api
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "5234:8080"
        depends_on:
            - booksaw-db
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ConnectionStrings__BookSawDb=Host=booksaw-db;Port=5432;Database=BookSawDb;Username=BookSaw;Password=BookSaw123
        networks:
            - booksaw-network
        entrypoint:
            - bash
            - -c
            - |
                dotnet BookSaw.Seeder.dll &&
                dotnet BookSaw.Api.dll

    booksaw-db:
        image: postgres:latest
        container_name: booksaw-db
        restart: always
        environment:
            POSTGRES_DB: BookSawDb
            POSTGRES_USER: BookSaw
            POSTGRES_PASSWORD: BookSaw123
        volumes:
            - booksaw-db-volume:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - booksaw-network

volumes:
    booksaw-db-volume:

networks:
    booksaw-network:
