name: booksaw

services:
    booksaw-proxy:
        image: nginx:latest
        container_name: booksaw-proxy
        restart: always
        ports:
            - "80:80"
        volumes:
            - ./nginx/booksaw-proxy.conf:/etc/nginx/conf.d/default.conf
        networks:
            - booksaw-network

    booksaw-website:
        image: ghcr.io/he1enm/booksaw.website:latest
        container_name: booksaw-website
        restart: always

        networks:
            - booksaw-network

    booksaw-db:
        image: postgres:latest
        container_name: booksaw-db
        restart: always
        environment:
            POSTGRES_DB: BookSawDb
            POSTGRES_USER: BookSaw
            POSTGRES_PASSWORD: BookSaw123
        volumes:
            - booksaw-db-volume:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - booksaw-network

    booksaw-api:
        build: .
        container_name: booksaw-api
        restart: always

        ports:
            - "8080:80"
        depends_on:
            - booksaw-db
        environment:
            - TZ=Europe/Chisinau
            - ASPNETCORE_ENVIRONMENT=Development
            - DOTNET_ENVIRONMENT=Development
            - AllowedHosts=*
            - Logging:LogLevel:Default=Warning
            - Logging:LogLevel:Microsoft.Hosting.Lifetime=Information
            - Logging:LogLevel:BookSaw.Api=Information
            - Logging:LogLevel:BookSaw.Seeder=Debug
            - ConnectionStrings__BookSawDb=Host=booksaw-db;Port=5432;Database=BookSawDb;Username=BookSaw;Password=BookSaw123
        networks:
            - booksaw-network
        entrypoint:
            - bash
            - -c
            - |
                dotnet tools/BookSaw.Seeder.dll &&
                dotnet BookSaw.Api.dll

volumes:
    booksaw-db-volume:

networks:
    booksaw-network:
